PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS cheque;
CREATE TABLE cheque (id INTEGER PRIMARY KEY AUTOINCREMENT, ch_id TEXT NOT NULL, datetime TEXT NOT NULL, inn TEXT NOT NULL, orgName TEXT NOT NULL, orgAddress TEXT NOT NULL, seller TEXT NOT NULL, paymentNal REAL NOT NULL DEFAULT (0), paymentBeznal REAL NOT NULL DEFAULT (0), paymentCert REAL NOT NULL DEFAULT (0), sdacha REAL NOT NULL DEFAULT (0), totals REAL NOT NULL DEFAULT (0));

DROP TABLE IF EXISTS cheque_line;
CREATE TABLE cheque_line (id INTEGER PRIMARY KEY AUTOINCREMENT, cheque_id INTEGER NOT NULL REFERENCES cheque (id) ON DELETE CASCADE ON UPDATE CASCADE, lineNumber INTEGER NOT NULL DEFAULT (0), artikul TEXT NOT NULL, barcode TEXT NOT NULL, name TEXT NOT NULL DEFAULT "", quantity INTEGER NOT NULL DEFAULT (0), price REAL NOT NULL DEFAULT (0), discountPercent REAL NOT NULL DEFAULT (0), discount REAL NOT NULL DEFAULT (0), summ REAL NOT NULL DEFAULT (0));

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
